unstable_features = true
wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true

ignore = [
    "walletd/mnemonics"
]
